[package]
name = "rwam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
fuse_mt = "0.6.0"
fuser = "0.13.0"
libc = "0.2.148"
